### ISSUE TITLE
feat: Realm의 CRUD 기능을 다룹니다

### ISSUE THREAD

**Issue by dayo2n** [Damagucci-Juice/2023-SK-Prompt-DengChat#13]
# Description
@Damagucci-Juice 구찌 자는동안 한 번 만져볼게요 작업내용은 여기 스레드 + 커밋메시지로 전달합니다
feature/customCalendar에서 브랜치를 따옵니다

# TODO
## Create
- [x] DailyNote나 DogState, NoteGroup은 SwiftRealm의 Object 타입의 서브클래스이기 때문에 수퍼클래스의 designated init을 호출하고convenience 이니셜라이저로 서브클래스의 값들을 초기화해줍니다
- [x] 데이터베이스 모델 객체가 생성될 때마다 다시 ObjectId를 생성해줍니다: 같은 키로 update가 아닌 add하려고 하면 오류나요
- [x] DailyNote의 DogState 프로퍼티가 옵셔널이어야 한대요. 원인은 안찾아봄!!
<img width="849" alt="스크린샷 2023-09-03 오전 3 59 44" src="https://github.com/Damagucci-Juice/2023-SK-Prompt-DengChat/assets/57654681/98ba9f8d-c354-4d81-b5c4-abda0edbcfcf">

## Read
- [x] posted를 Date로 저장하면 쿼리때마다 KST 서울시간으로 변환해서 비교해야함 → String으로 일단 시간은 짤라서 저장했어요 
- [x] 선택된 날짜와 같은 날짜의 note들을 읽어오는 read() 기능 구현
- 확인해보니까 순서대로 저장되고 읽어와서 순서가 필요하다면 인덱스를 이용하면 될듯요
- **Realm()이 불러와지지 않는다면 다른 기기 또는 시뮬레이터로 구동해보세요**
<img width="1060" alt="스크린샷 2023-09-03 오전 5 12 44" src="https://github.com/Damagucci-Juice/2023-SK-Prompt-DengChat/assets/57654681/cd80e6e9-7d7d-46d0-8469-47dac25a04e3">
<img width="303" alt="스크린샷 2023-09-03 오전 5 12 23" src="https://github.com/Damagucci-Juice/2023-SK-Prompt-DengChat/assets/57654681/a9e33caa-f0f9-4bb6-91c2-9383bbb15e92">

## Delete
- [x] note를 지우면서 DogState도 함께 삭제
- realm.wrtie() 한 번에 delete 한 번이네요. 지울 날짜의 노트들에 연관된 DogState._id를 읽어와서 먼저 삭제해준 이후 DailyNote를 삭제했습니다.
![ezgif com-video-to-gif (16)](https://github.com/Damagucci-Juice/2023-SK-Prompt-DengChat/assets/57654681/d4a1f115-665d-4863-ae48-6a3a4d4fea54)

## to Gucci
- [ ] DailyNote와 DiaryHandler에서 stripDate(Date)->String 함수를 정의해서 쓰고 있는데, extension Date에 정의해서 쓰려니까 애들이 인식을 못하네요 수정 필요
- update는 필요없는 함수네요! 안했습니닷
