### ISSUE TITLE
feat: 일기뷰 이후 화면 구현

### ISSUE THREAD

**Issue by dayo2n** [Damagucci-Juice/2023-SK-Prompt-DengChat#16]
# Description
나머지 화면을 구현하고 챗뷰와 다이어리에 미디파이가 덜 적용된 것들을 수정합니다

# TODO
- [x] 첫 화면
- [ ] 챗봇뷰
  - [x] 채팅 입력 필드 디자인 수정
  - [x] 도움말
  - [ ] '산책' 키워드가 있으면 산책 다녀왔따. 없으면 산책을 못가서 가고싶어 할거다.
- [x] 그림일기뷰
  - [x] 하단 버튼들
  - [x] 도움말
  - [x] 저장 누르고 저장완료되면 팝업
  - [x] 추천활동 뷰
    - [ ] 우울증 극복
    - [ ] 가까운 병원찾기 (지도 넣고 병원 추천은 뷰만)
